# Generated by Django 4.1.1 on 2022-09-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_auto_20200806_1144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
